### ISSUE TITLE
small bugs in readme.md react example

### ISSUE THREAD

**Issue by derdanielmoin** [farskid/sockette-component#1]
Hi,

thanks for sharing this. It helps me to understand a bit more about react and websockets. There are a few small errors that I found in the example for react. These are:
- 'const Socket = createSocket({' should be  'const Sockette = createSocket({'
- 'this.stte.ws.send("Hello, world!");' should be 'this.state.ws.send("Hello, world!");'
- 'this.setState(socket)' should be 'this.setState({socket})'
would be cool if you fix these.
Best regards,
Daniel

**Comment by kaiserama** [comment]
I would also add that the button code:

`<button onclick={this.sendMessage}>SEND</button>`

Should be:

`<button onClick={this.sendMessage}>SEND</button>` - upper case C

Additionally, 

`this.stte.ws.send("Hello, world!");`

Should be:

`this.state.socket.send("Hello, world!");`

To reiterate the OP, thanks for sharing this component.  I think it's a really useful tool for working with WebSockets (vanilla ones)!

**Comment by farskid** [comment]
@derdanielmoin @kaiserama Thanks for reaching out and sorry for the delay. I happened to turned off the watch on this repo by accident!

I'd try to update Readme ASAP.
